ARG BASE_IMAGE=pcla-wrapper:common-slim
FROM ${BASE_IMAGE}

COPY . /opt/pcla-pretrained

RUN test -f /opt/pcla-pretrained/pcla-weight-profile.json \
    && /opt/pcla-venv/bin/python /app/scripts/validate_common_runtime.py \
        --check-weights

ENV PCLA_WEIGHTS_BUNDLED=1
